# -*- coding: utf-8 -*-
"""analise1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e4jsW2ncAt0HHp6nzC76Ic7CAwictmhD
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

detran = pd.read_csv(r'dados.csv', encoding='ISO-8859-1',sep=' ')

df_detran = pd.DataFrame(detran)
df_detran

mg = df_detran.loc[df_detran["uf"] == "MG"]

sns.set_style("dark")
ax = sns.countplot(y = 'uf', data = df_detran, color = 'red', order= df_detran['uf'].value_counts().index)
ax.set(xlabel=None)
ax.set(xticklabels=[])
plt.title("Número de Ocorrências por Estados")
#plt.xlabel("Ocorrências")
plt.ylabel("Estados")
plt.show()

# filtrando df para top 27 municipios
df_municipios = df_detran['municipio'].value_counts().head(27)
df_municipios

#plot para os municipios
sns.set_style("dark")
ax = sns.countplot(y = 'municipio', data = df_detran, color = 'red', order= df_detran['municipio'].value_counts().head(27).index)
ax.set(xlabel=None)
ax.set(xticklabels=[])
plt.title("Número de casos por Munícipios")
#plt.xlabel("Ocorrências")
plt.ylabel("Estados")
plt.show()

#plot para os municipios
sns.set_style("dark")
ax = sns.countplot(y = 'dia_semana', data = df_detran, color = 'red', order= df_detran['dia_semana'].value_counts().head(7).index)
ax.set(xlabel=None)
ax.set(xticklabels=[])
plt.title("Número de Ocorrências por Munícipios")
plt.xlabel("Ocorrências")
plt.ylabel("Estados")
plt.show()

#plot para os municipios
sns.set_style("dark")
ax = sns.countplot(y = 'tipo_acidente', data = df_detran, color = 'red', order= df_detran['tipo_acidente'].value_counts().head(7).index)
ax.set(xlabel=None)
ax.set(xticklabels=[])
plt.title("Número de Ocorrências por Munícipios")
plt.xlabel("Ocorrências")
plt.ylabel("Estados")
plt.show()

# filtrando df para top 15 causas
df_causa = df_detran['causa_acidente'].value_counts().head(15)
df_causa

sns.set_style("dark")
ax = sns.countplot(y = 'causa_acidente', data = df_detran, color = 'red', order= df_detran['causa_acidente'].value_counts().head(10).index)
#ax.bar_label(ax.containers[0])
ax.set(xlabel=None)
ax.set(xticklabels=[])
plt.title("10 Principais Causas de Acidentes")
plt.xlabel("Casos")
plt.ylabel("")
plt.show()